name: Main Workflow

on:
  pull_request: {}
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'
    paths-ignore:
      - 'docs/*'

jobs:
  build:
    name: Build Shoutrrr
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: CGO_ENABLED=0 go build -v .

      - name: Test
        run: CGO_ENABLED=0 go test -v -coverprofile=coverage.out -covermode=atomic ./...

      - name: Publish coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
